version: '3'

services:
<<<<<<< HEAD
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    command: sh -c "yarn start"
    ports:
     - 3000:3000
    tty: true
    restart: always
=======
  react_app:
    container_name: react_app
    build: ./
    command: sh -c "yarn start"
    volumes:
      - ./:/usr/src/app
    ports:
     - "3000:3000"
    restart: always

>>>>>>> master
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./build:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
<<<<<<< HEAD
      - react
    restart: always
=======
      - react_app

>>>>>>> master
networks:
  default:
    external:
      name: shared