version: '3'

services:
  react_app:
    container_name: react_app
    build: ./
    command: sh -c "yarn start"
    volumes:
      - ./:/usr/src/app
    ports:
     - "3000:3000"
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./build:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - react_app

networks:
  default:
    external:
      name: shared